version: "2"
services:

    php:
        container_name: php-dockerigniter
        build: ./resources/docker/php
        volumes:
            - ./:/var/www/html
        expose:
            - 8989
        ports:
            - 8989:80
        links: 
            - mysql
            - redis

    mysql:
        container_name: mysql-dockerigniter
        image: mysql:5.7
        restart: always
        environment:
          MYSQL_DATABASE: 'dockerigniter'
          MYSQL_USER: 'admin'
          MYSQL_PASSWORD: 'Foo1234'
          MYSQL_ROOT_PASSWORD: 'Foo1234'
        ports:
          - '3306:3306'
        expose:
          - '3306'
        volumes:
          - ./resources/docker/persistence/mysql:/var/lib/mysql

    redis:
        container_name: redis-dockerigniter
        image: redis
        ports:
            - "6379:6379"
        volumes:
            - ./resources/docker/persistence/redis:/data
